version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: evo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: evo_user
      POSTGRES_PASSWORD: evo_password
      POSTGRES_DB: evo_orders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evonet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U evo_user -d evo_orders_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: evo-api-gateway
    ports:
      - "8000:8000"
    environment:
      - ORDER_SERVICE_URL=http://order-service:8001
      - INVENTORY_SERVICE_URL=http://inventory-service:8002
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

    depends_on:
      - order-service
      - inventory-service
    networks:
      - evonet

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: evo-order-service
    ports:
      - "8001:8001"
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8002
      - PAYMENT_SERVICE_URL=http://payment-service:8003
      - NOTIFICATION_SERVICE_URL=http://notification-service:8004
      - DATABASE_URL=postgresql+psycopg2://evo_user:evo_password@postgres:5432/evo_orders_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

    depends_on:
      postgres:
        condition: service_healthy
      inventory-service:
        condition: service_started
      payment-service:
        condition: service_started
      notification-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy

    networks:
      - evonet

  inventory-service:
    build:
      context: ./services/inventory-service
      dockerfile: Dockerfile
    container_name: evo-inventory-service
    ports:
      - "8002:8002"
    environment:
      - REDIS_URL=redis://redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - evonet

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: evo-payment-service
    ports:
      - "8003:8003"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

    networks:
      - evonet

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: evo-notification-service
    ports:
      - "8004:8004"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - evonet

  redis:
    image: redis:7-alpine
    container_name: evo-redis
    ports:
      - "6379:6379"
    networks:
      - evonet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: evo-rabbitmq
    ports:
      - "5672:5672" # AMQP message broker port
      - "15672:15672" # Web UI Dashboard port
    networks:
      - evonet
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: evo-jaeger
    ports:
      - "16686:16686" # Web UI (Search & view traces)
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - evonet

  prometheus:
    image: prom/prometheus:latest
    container_name: evo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - evonet


volumes:
  postgres_data:

networks:
  evonet:
    driver: bridge
